"""Non-human English plumbing fixture generated by the provisioned eSpeak NG library."""

import audioop
import ctypes
import hashlib
import json
import wave
from pathlib import Path

import espeakng_loader

ROOT = Path(__file__).resolve().parents[1]
TEXT = "Where are my blue keys?"


def main():
    library = ctypes.CDLL(espeakng_loader.get_library_path())
    library.espeak_Initialize.argtypes = [ctypes.c_int, ctypes.c_int, ctypes.c_char_p, ctypes.c_int]
    library.espeak_Initialize.restype = ctypes.c_int
    data = Path(espeakng_loader.get_data_path())
    rate = library.espeak_Initialize(2, 0, str(data.parent).encode(), 0x8000)
    if rate <= 0:
        raise RuntimeError("Synthetic speech library initialization failed")
    chunks = []
    callback_type = ctypes.CFUNCTYPE(
        ctypes.c_int, ctypes.POINTER(ctypes.c_short), ctypes.c_int, ctypes.c_void_p
    )

    @callback_type
    def callback(pointer, count, events):
        if pointer and count > 0:
            chunks.append(ctypes.string_at(pointer, count * 2))
        return 0

    library.espeak_SetSynthCallback.argtypes = [callback_type]
    library.espeak_SetSynthCallback(callback)
    library.espeak_SetVoiceByName.argtypes = [ctypes.c_char_p]
    assert library.espeak_SetVoiceByName(b"en-us") == 0
    library.espeak_Synth.argtypes = [
        ctypes.c_void_p,
        ctypes.c_size_t,
        ctypes.c_uint,
        ctypes.c_int,
        ctypes.c_uint,
        ctypes.c_uint,
        ctypes.POINTER(ctypes.c_uint),
        ctypes.c_void_p,
    ]
    text = ctypes.create_string_buffer(TEXT.encode())
    assert library.espeak_Synth(text, len(text), 0, 1, 0, 1, None, None) == 0
    library.espeak_Terminate()
    raw, _ = audioop.ratecv(b"".join(chunks), 2, 1, rate, 16000, None)
    assert 0 < len(raw) <= 320000
    path = ROOT / "voice/evidence/synthetic-input.wav"
    with wave.open(str(path), "wb") as wav:
        wav.setparams((1, 2, 16000, 0, "NONE", "not compressed"))
        wav.writeframes(raw)
    (path.with_suffix(".json")).write_text(
        json.dumps(
            {
                "text": TEXT,
                "source": "locally generated eSpeak NG en-us synthetic speech; not a human recording",
                "engine_license": "GPL-3.0-or-later; bundled loader notices retained",
                "original_text": "non-sensitive test phrase",
                "duration_seconds": len(raw) / 32000,
                "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
                "purpose": "plumbing only; no human/Taglish recognition-quality acceptance",
            },
            indent=2,
        )
        + "\n"
    )
    print("SYNTHETIC_INPUT", len(raw) / 32000)


if __name__ == "__main__":
    main()
