// Local integration; never grants actual microphone/camera permission.
const {chromium} = require(process.env.PLAYWRIGHT_MODULE || require('node:path').join(require('node:os').homedir(), '.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
const {spawn} = require('node:child_process');
const fs = require('node:fs'); const os = require('node:os'); const path = require('node:path');
const assert = require('node:assert/strict');
const ROOT = path.resolve(__dirname, '..'); const OUT = path.join(ROOT, 'deliverables/nook-integration');
const PORT = 8766, base = `http://127.0.0.1:${PORT}`;
let testPage;
const temp = fs.mkdtempSync(path.join(os.tmpdir(), 'local-memory-browser-'));
let server, browser; const results = [], errors = [], external = [];
const log = fs.openSync(path.join(OUT, 'server-test.log'), 'w');
function check(name, truth) { assert.ok(truth, name); results.push(name); console.log('PASS', name); }
async function waitForServer() { for (let i = 0; i < 80; i++) { if(server.exitCode!==null) throw Error('Owned server exited before readiness'); try { if (fs.readFileSync(path.join(OUT,'server-test.log'),'utf8').includes(`Uvicorn running on ${base}`) && (await fetch(base+'/api/status')).ok) return; } catch {} await new Promise(r=>setTimeout(r,100)); } throw Error('Local server failed to start'); }
function startServer() { server = spawn(process.env.APP_TEST_PYTHON || path.join(ROOT,'.venv/bin/python'), ['-m','app'], {cwd:ROOT, env:{...process.env, APP_DATA_DIR:temp, APP_PORT:String(PORT), APP_VISION_DISABLED:'1', APP_VOICE_ENABLED:'0', APP_TEXT_MODEL:''}, stdio:['ignore',log,log]}); return waitForServer(); }
async function stopServer() { if (server && server.exitCode === null) { server.kill('SIGTERM'); await new Promise(r=>server.once('exit',r)); } }
(async()=>{ try {
  await startServer(); browser = await chromium.launch({headless:true, executablePath:process.env.CHROMIUM_EXECUTABLE || path.join(os.homedir(),'.cache/ms-playwright/chromium-1234/chrome-linux64/chrome'), args:['--disable-gpu','--renderer-process-limit=2']});
  const context = await browser.newContext({viewport:{width:1280,height:1000}}); const page = await context.newPage(); testPage=page; page.setDefaultTimeout(10000); page.on('pageerror',e=>errors.push(e.message));
  await context.route('**/*', route=>{ if (!route.request().url().startsWith(base)) { external.push(route.request().url()); return route.abort(); } return route.continue(); });
  await page.goto(base); await page.locator('#onboard-next').click(); await page.locator('#onboarding').waitFor({state:'hidden'}); check('Onboarding completes and persists',await page.evaluate(()=>localStorage.getItem('nook.onboarded')==='1')); await page.waitForFunction(()=>document.querySelector('#speech-state').textContent.includes('speech is off'));
  check('Typing fallback when real speech is off', await page.locator('#record').isDisabled());
  await page.waitForFunction(()=>getComputedStyle(document.querySelector('main')).opacity==='1'); await page.screenshot({path:path.join(OUT,'talk-desktop.png'),fullPage:true,animations:'disabled'});
  await page.locator('#utterance').fill('Where is my passport?'); await page.locator('#ask').click(); await page.getByText('No matching memory yet.',{exact:true}).waitFor(); check('Real API not-found recall', true);
  await page.locator('nav a[data-page=capture]').click(); await page.locator('#capture').waitFor({state:'visible'}); await page.locator('#photo-file').setInputFiles(path.join(ROOT,'tests/fixtures/vision/keys.jpg')); await page.locator('#draft').waitFor({state:'visible'});
  await page.locator('#item-name').fill('House keys'); await page.locator('#item-location').fill('Hall cabinet, top drawer');
  await page.locator('#review-memory').click(); check('Explicit confirmation is required before saving',await page.locator('#save-memory').isDisabled()); check('Unchecked confirmation did not save', (await (await fetch(base+'/api/status')).json()).item_count === 0);
  await page.locator('#review-title').focus(); await page.screenshot({path:path.join(OUT,'capture-desktop.png'),fullPage:true,animations:'disabled'});
  await page.locator('#confirm-save').check(); await page.locator('#save-memory').dblclick(); await page.locator('#saved .card').waitFor(); check('Repeated submission saves one item', (await (await fetch(base+'/api/status')).json()).item_count === 1);
  await page.setViewportSize({width:390,height:1100}); await page.screenshot({path:path.join(OUT,'saved-mobile.png'),fullPage:true,animations:'disabled'});
  check('Mobile no horizontal overflow', await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.locator('#saved .card button').click(); await page.locator('#detail').waitFor({state:'visible'}); check('Saved source, date and unverified location visible', (await page.locator('#detail').innerText()).includes('Not a live location.') && (await page.locator('#detail').innerText()).includes('Confirmed imported photo'));
  await page.locator('#new-location').fill('Kitchen shelf'); await page.getByRole('button',{name:'Confirm location update',exact:true}).click(); await page.getByText('Last recorded: Kitchen shelf',{exact:true}).first().waitFor(); check('Real API location update',true);
  check('Historical photo survives move, current card has no old photo', await page.locator('#detail .card img').count()===0 && await page.locator('#detail .history img').count()===1);
  await page.getByRole('button',{name:'Mark moved / unknown'}).click(); await page.locator('#confirm-action').click(); await page.getByText('Location unknown',{exact:true}).first().waitFor(); check('Real API moved/unknown',true);
  await page.locator('#close-detail').click(); await page.reload(); await page.locator('#saved .card').waitFor(); check('Reload retains saved memory',await page.locator('#saved .card').count()===1);
  await stopServer(); await startServer(); await page.reload(); await page.locator('#saved .card').waitFor(); check('Real service restart retains memory',true);
  await page.locator('nav a[data-page=capture]').click(); await page.locator('#capture').waitFor({state:'visible'}); await page.locator('#photo-file').setInputFiles(path.join(ROOT,'tests/fixtures/vision/keys.jpg')); await page.locator('#draft').waitFor({state:'visible'}); const draftId = await page.evaluate(()=>sessionStorage.getItem('pendingCapture'));
  await page.reload(); await page.waitForFunction(()=>sessionStorage.getItem('pendingCapture')===null); check('Reload discards unsaved draft', await page.evaluate(async id=>(await fetch('/api/captures/'+id)).status,draftId)===404);
  await page.locator('#photo-file').setInputFiles(path.join(ROOT,'tests/fixtures/vision/keys.jpg')); await page.locator('#draft').waitFor({state:'visible'}); const backId=await page.evaluate(()=>sessionStorage.getItem('pendingCapture')); await page.goBack(); await page.locator('#decline-action').click(); check('Keep editing preserves draft',await page.locator('#draft').isVisible()); await page.locator('nav a[data-page=saved]').click(); await page.locator('#confirm-action').click(); await page.locator('#saved').waitFor({state:'visible'}); check('Browser back discards draft',await page.evaluate(async id=>(await fetch('/api/captures/'+id)).status,backId)===404);
  await page.locator('nav a[data-page=talk]').click(); await page.locator('#utterance').fill('House keys'); await page.locator('#ask').click(); await page.getByText('The item is saved. Its location is unknown.',{exact:true}).waitFor(); check('Known item with unknown location is distinct from not-found',true);
  // Slow provider/transport result is deliberately mocked and must be discarded after cancel.
  await page.route('**/api/recall',async route=>{await new Promise(r=>setTimeout(r,500)); await route.fulfill({json:{kind:'unknown',items:[],total:0}}).catch(()=>{});});
  await page.locator('#utterance').fill('House keys'); await page.locator('#ask').click(); await page.locator('#cancel-talk').click(); await page.waitForTimeout(700); check('Cancelled late response cannot repaint results',(await page.locator('#answer').innerText()).includes('Stopped.')); await page.unroute('**/api/recall');
  await page.setViewportSize({width:320,height:780}); check('320px reflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.locator('#utterance').focus(); await page.keyboard.press('Tab'); await page.keyboard.press('Tab'); check('Keyboard-focusable send action with visible focus',await page.locator('#ask').evaluate(e=>e===document.activeElement && getComputedStyle(e).outlineStyle==='solid'));
  // Make second record through the real API, including a shared alias for ambiguity.
  await page.evaluate(async()=>{const s=await(await fetch('/api/session')).json();const st=await(await fetch('/api/status')).json();window.testCsrf=s.csrf_token; for(const name of ['Spare keys','Travel keys']){await fetch('/api/items',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':s.csrf_token},body:JSON.stringify({confirmed:true,write_epoch:st.write_epoch,idempotency_key:crypto.randomUUID(),personal_name:name,aliases:['keyring'],location:'Desk drawer'})});}});
  await page.reload(); await page.waitForFunction(()=>document.querySelector('#speech-state').textContent.includes('speech is off')); await page.locator('#utterance').fill('keyring'); await page.locator('#ask').click(); await page.getByText('Which item did you mean?',{exact:true}).waitFor(); check('Ambiguous recall shows two separate records',await page.locator('#answer .card').count()===2);

  // Real commit with a deliberately lost response: retry must replay the same receipt.
  await page.locator('nav a[data-page=capture]').click(); await page.locator('#capture').waitFor({state:'visible'});

  await page.locator('#photo-file').setInputFiles(path.join(ROOT,'tests/fixtures/vision/keys.jpg')); await page.locator('#draft').waitFor({state:'visible'});
  await page.locator('#identity').selectOption({label:'House keys'}); await page.locator('#item-location').fill('Old photo: hall table'); await page.locator('#make-current').uncheck(); await page.locator('#review-memory').click(); await page.locator('#confirm-save').check(); await page.locator('#save-memory').click(); await page.locator('#saved').waitFor({state:'visible'});
  check('Existing-item historical capture does not create duplicate or assert current location',(await(await fetch(base+'/api/status')).json()).item_count===3);
  await page.locator('#saved .card').filter({has:page.getByRole('heading',{name:'House keys',exact:true})}).getByRole('button').click(); await page.locator('#detail').waitFor({state:'visible'});
  check('Historical capture preserves unknown current location',(await page.locator('#detail .card').innerText()).includes('Location unknown'));
  let trapped=true; for(let i=0;i<8;i++){await page.keyboard.press('Tab');trapped=trapped&&await page.locator('#detail').evaluate(e=>e.contains(document.activeElement));}check('Native detail dialog retains keyboard focus',trapped); await page.keyboard.press('Escape');check('Escape closes idle detail dialog',!(await page.locator('#detail').isVisible()));
  await page.locator('nav a[data-page=capture]').click(); await page.locator('#capture').waitFor({state:'visible'});
  await page.locator('#photo-file').setInputFiles({name:'bad.png',mimeType:'image/png',buffer:Buffer.from('invalid image')}); await page.waitForFunction(()=>document.querySelector('#notice').classList.contains('error')); check('Malformed upload reports error without creating memory',(await(await fetch(base+'/api/status')).json()).item_count===3);
  await page.locator('#photo-file').setInputFiles(path.join(ROOT,'tests/fixtures/vision/keys.jpg')); await page.locator('#draft').waitFor({state:'visible'});
  await page.locator('#item-name').fill('Retry test keys'); await page.locator('#item-location').fill('Study shelf'); await page.locator('#review-memory').click(); await page.locator('#confirm-save').check();
  let firstCommit, replayCommit, commitCount=0;
  await page.route('**/api/captures/*/commit',async route=>{commitCount++;if(commitCount===1){firstCommit=route.request().postData();await route.fetch();await route.abort('failed');}else{replayCommit=route.request().postData();await route.continue();}});
  await page.locator('#save-memory').click(); await page.waitForFunction(()=>document.querySelector('#save-error').textContent.length>0);
  await page.locator('nav a[data-page=saved]').click(); await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('pending save')); check('Uncertain save freezes reviewed fields',await page.locator('#item-name').isDisabled()); check('Uncertain save blocks navigation',await page.locator('#capture').isVisible());
  await page.locator('#save-memory').click(); await page.locator('#saved').waitFor({state:'visible'}); await page.waitForFunction(()=>document.querySelectorAll('#saved .card').length===4);
  check('Lost commit response retries exact idempotency payload without duplicate',firstCommit===replayCommit&&(await(await fetch(base+'/api/status')).json()).item_count===4); await page.unroute('**/api/captures/*/commit');
  // Script-like personal names are text, never HTML.
  await page.evaluate(async()=>{const s=await(await fetch('/api/session')).json();const st=await(await fetch('/api/status')).json();await fetch('/api/items',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':s.csrf_token},body:JSON.stringify({confirmed:true,write_epoch:st.write_epoch,idempotency_key:crypto.randomUUID(),personal_name:'<img src=x onerror=alert(1)>',location:'Fixture shelf'})});});
  await page.reload(); await page.waitForFunction(()=>document.querySelectorAll('#saved .card').length===5); check('Untrusted saved labels render as literal text',await page.getByRole('heading',{name:'<img src=x onerror=alert(1)>',exact:true}).count()===1 && await page.locator('img[src=x]').count()===0);
  await page.locator('nav a[data-page=talk]').click(); await page.locator('#talk').waitFor({state:'visible'});

  // Software fixtures only: fake media stream/AudioContext and mocked STT/TTS transport.
  await page.route('**/api/status',async route=>{const res=await route.fetch();const json=await res.json();json.speech.provider_enabled=true;json.speech.artifacts_present=true;await route.fulfill({json});});
  await page.addInitScript(()=>{
    window.fakeMedia={requested:0,stopped:0};
    Object.defineProperty(navigator.mediaDevices,'getUserMedia',{configurable:true,value:async()=>{window.fakeMedia.requested++;return {getTracks:()=>[{stop:()=>window.fakeMedia.stopped++}]};}});
    window.AudioContext=class{constructor(){this.sampleRate=16000;this.state='running';this.audioWorklet={addModule:async()=>{}};this.destination={};}createMediaStreamSource(){return {connect(){},disconnect(){}};}resume(){return Promise.resolve();}close(){this.state='closed';return Promise.resolve();}};
    window.AudioWorkletNode=class{constructor(){this.port={onmessage:null};}connect(){setTimeout(()=>this.port.onmessage?.({data:Float32Array.from({length:1600},(_,i)=>Math.sin(i/4)*.3)}),20);}disconnect(){}};
  });
  let transcriptions=0, spoken=0;
  await page.route('**/api/speech/transcribe',async route=>{transcriptions++; const input=route.request().postDataJSON();const wav=Buffer.from(input.audio.data_base64,'base64');assert.equal(wav.toString('ascii',0,4),'RIFF');assert.equal(wav.readUInt32LE(24),16000);await route.fulfill({json:{transcript:'House keeps',persisted:false,transcript_confirmed:false}});});
  const audio=fs.readFileSync(path.join(ROOT,'voice/evidence/kokoro-readback-16k.wav')).toString('base64');
  await page.route('**/api/speech/turns',async route=>{spoken++;const input=route.request().postDataJSON();assert.equal(input.utterance,'House keys');assert.equal(input.transcript_confirmed,true);await route.fulfill({json:{reply_text:'Fixture reply: current location is unverified.',recall:{kind:'unknown',items:[]},speech:{audio_base64:audio,content_type:'audio/wav'}}});});
  await page.reload(); await page.waitForFunction(()=>!document.querySelector('#record').disabled); check('No automatic media request',await page.evaluate(()=>fakeMedia.requested)===0);
  await page.locator('#record').click(); await page.locator('#stop-record').waitFor({state:'visible'}); await page.waitForTimeout(80); await page.locator('#stop-record').click(); await page.waitForFunction(()=>document.querySelector('#utterance').value==='House keeps'); check('Mock transcription is editable and not automatically submitted',transcriptions===1&&spoken===0);
  await page.locator('#utterance').fill('House keys'); await page.locator('#open-settings').click(); await page.locator('#speak-reply').check(); await page.locator('#close-settings').click(); await page.locator('#ask').click(); await page.locator('#answer audio').waitFor(); check('Confirmed edited transcript; returned speech has manual playback controls',spoken===1&&await page.locator('#answer audio').evaluate(a=>a.controls&&!a.autoplay&&a.paused));
  await page.locator('#record').click(); await page.locator('#cancel-talk').click(); check('Cancel removes returned audio and transcript',await page.locator('#answer audio').count()===0&&await page.locator('#utterance').inputValue()==='');
  await page.locator('#record').click(); await page.locator('#stop-record').waitFor({state:'visible'}); await page.locator('nav a[data-page=saved]').click(); await page.locator('#saved').waitFor({state:'visible'}); check('Mock recording tracks stop on navigation',await page.evaluate(()=>fakeMedia.stopped)>=2);
  await page.locator('#saved .card').first().getByRole('button').click(); await page.locator('#detail').waitFor({state:'visible'}); let deletePayload, retryDeletePayload, deleted=0;
  await page.route('**/api/items/*',async route=>{if(route.request().method()!=='DELETE')return route.continue();deleted++;if(deleted===1){deletePayload=route.request().postData();await route.fetch();return route.abort('failed');}retryDeletePayload=route.request().postData();return route.continue();});
  await page.getByRole('button',{name:'Delete this memory'}).click(); await page.locator('#confirm-action').click(); await page.locator('#detail-error').waitFor(); await page.locator('#close-detail').click(); check('Uncertain deletion keeps retry accessible',await page.locator('#detail').isVisible());
  await page.getByRole('button',{name:'Delete this memory'}).click(); await page.locator('#confirm-action').click(); await page.waitForFunction(()=>!document.querySelector('#detail').open); check('Lost deletion response retries exact receipt despite item already deleted',deletePayload===retryDeletePayload); await page.unroute('**/api/items/*'); check('Delete integrates with real backend', (await (await fetch(base+'/api/status')).json()).item_count===4);

  await page.locator('nav a[data-page=talk]').click(); await page.locator('#talk').waitFor({state:'visible'});
  await page.evaluate(()=>Object.defineProperty(navigator.mediaDevices,'getUserMedia',{configurable:true,value:()=>new Promise(resolve=>window.resolvePermission=resolve)}));
  await page.locator('#record').click(); await page.waitForFunction(()=>!!window.resolvePermission); await page.locator('#cancel-talk').click(); const stoppedBefore=await page.evaluate(()=>fakeMedia.stopped);
  await page.evaluate(()=>window.resolvePermission({getTracks:()=>[{stop:()=>fakeMedia.stopped++}]})); await page.waitForFunction(previous=>fakeMedia.stopped>previous,stoppedBefore); check('Late mocked microphone permission is stopped after cancellation',await page.locator('#stop-record').isHidden());
  // Provider error is injected, not a real inference test.
  await page.unroute('**/api/speech/turns'); await page.route('**/api/speech/turns',route=>route.fulfill({status:504,json:{error:{message:'Speech timed out. Type your text.'}}}));
  await page.locator('#open-settings').click(); await page.locator('#speak-reply').check(); await page.locator('#close-settings').click(); await page.locator('#utterance').fill('House keys'); await page.locator('#ask').click(); await page.waitForFunction(()=>document.querySelector('#answer').textContent.includes('timed out')); check('Provider timeout is visible and reviewed text remains editable',await page.locator('#utterance').inputValue()==='House keys'); check('Speech failure automatically returns the next attempt to typed mode',!(await page.locator('#speak-reply').isChecked())); await page.locator('#ask').click(); await page.locator('#answer .card').waitFor(); check('Typed fallback succeeds through real API after provider failure',true);

  await page.evaluate(()=>Object.defineProperty(navigator.mediaDevices,'getUserMedia',{configurable:true,value:async()=>{const canvas=document.createElement('canvas');canvas.width=96;canvas.height=96;canvas.getContext('2d').fillRect(0,0,96,96);window.mockCameraCanvas=canvas;const stream=canvas.captureStream(2);window.mockCameraStream=stream;return stream;}}));
  await page.locator('nav a[data-page=capture]').click(); await page.locator('#capture').waitFor({state:'visible'}); await page.locator('#camera-start').click(); await page.waitForFunction(()=>document.querySelector('#camera').videoWidth>0);
  await page.locator('#take-photo').click(); await page.locator('#draft').waitFor({state:'visible'}); check('Mock camera frame enters real photo review without saving memory',(await(await fetch(base+'/api/status')).json()).item_count===4 && (await page.locator('#draft-source').innerText()).includes('Camera frame'));
  check('Camera tracks stop after one deliberately selected frame',await page.evaluate(()=>mockCameraStream.getTracks().every(t=>t.readyState==='ended'))); await page.locator('#discard').click(); await page.locator('#draft').waitFor({state:'hidden'});
  await page.unroute('**/api/status'); await page.route('**/api/status',async route=>{const res=await route.fetch();const json=await res.json();json.speech.provider_enabled=true;json.speech.artifacts_present=false;await route.fulfill({json});}); await page.reload(); await page.waitForFunction(()=>document.querySelector('#speech-state').textContent.includes('files are unavailable')); check('Missing speech artifacts clearly disable recording without blocking typing',await page.locator('#record').isDisabled() && !(await page.locator('#ask').isDisabled()));
  await page.locator('#open-settings').click(); await page.locator('#appearance').selectOption('dark'); await page.locator('#reduce-motion').check(); await page.locator('#close-settings').click(); await page.reload();
  check('Appearance and motion preferences survive reload',await page.evaluate(()=>document.documentElement.dataset.theme==='dark'&&document.documentElement.dataset.motion==='reduce'&&document.querySelector('#onboarding').hidden));
  await page.locator('#open-settings').click(); await page.locator('#replay-onboarding').click(); await page.locator('#onboard-next').waitFor(); await page.screenshot({path:path.join(OUT,'onboarding-mobile.png')}); await page.locator('#onboard-next').click();
  await page.locator('nav a[data-page=capture]').click(); await page.locator('#manual-start').click(); await page.locator('#item-name').fill('Demo wallet'); await page.locator('#item-location').fill('Nightstand tray'); await page.locator('#review-memory').click();
  check('Manual memory remains unsaved before review confirmation',(await(await fetch(base+'/api/status')).json()).item_count===4);
  await page.locator('#confirm-save').check(); await page.locator('#save-memory').click(); await page.waitForFunction(()=>document.querySelectorAll('#saved .card').length===5);
  await page.locator('nav a[data-page=talk]').click(); await page.locator('#utterance').fill('Demo wallet'); await page.locator('#ask').click(); await page.locator('#answer').getByText('Last recorded: Nightstand tray',{exact:true}).waitFor(); check('Reviewed manual save recalls through real backend',true);
  await page.screenshot({path:path.join(OUT,'recall-mobile-dark.png'),fullPage:true,animations:'disabled'});
  await page.locator('#answer .card button').click(); await page.locator('summary').click(); await page.locator('#edit-aliases').fill('daily wallet'); await page.getByRole('button',{name:'Save item details',exact:true}).click(); await page.waitForFunction(()=>document.querySelector('#notice').textContent==='Memory details updated.'); await page.locator('#close-detail').click(); await page.locator('#utterance').fill('daily wallet'); await page.locator('#ask').click(); await page.locator('#answer').getByText('Last recorded: Nightstand tray',{exact:true}).waitFor(); check('Metadata alias edit is persisted and recalled',true);
  check('Final Nook document and public branding',await page.title()==='Nook · A little less searching' && (await page.locator('.wordmark').textContent()).trim()==='nook.');
  await stopServer(); await page.locator('#utterance').fill('daily wallet'); await page.locator('#ask').click(); await page.getByRole('button',{name:'Try question again'}).waitFor(); check('Service outage has a visible retry without losing typed question',await page.locator('#utterance').inputValue()==='daily wallet');
  await startServer(); await page.getByRole('button',{name:'Try question again'}).click(); await page.locator('#answer').getByText('Last recorded: Nightstand tray',{exact:true}).waitFor(); check('Restart renews CSRF session and retries through current UI',true);
  await page.setViewportSize({width:1280,height:900}); await page.locator('#open-settings').click(); await page.locator('#appearance').selectOption('light'); await page.locator('#close-settings').click(); await page.screenshot({path:path.join(OUT,'recall-desktop.png'),fullPage:true,animations:'disabled'});
  check('No page script errors',errors.length===0); check('No browser external requests observed',external.length===0);
  fs.writeFileSync(path.join(OUT,'browser-results.json'),JSON.stringify({passed:results.length,checks:results,pageErrors:errors,externalRequests:external,media:'Mocked browser devices and STT/TTS boundaries; no hardware permission granted. Real CRUD/recall/restart.',screenshots:'Local fixture records only; source attribution in README.'},null,2));
} catch(e) { console.error('UI', await testPage?.locator('#notice').innerText()); console.error('PAGE ERRORS',errors); await testPage?.screenshot({path:path.join(OUT,'failure.png'),fullPage:true,animations:'disabled'}); throw e; } finally { if(browser) await browser.close(); await stopServer(); fs.closeSync(log); fs.rmSync(temp,{recursive:true,force:true}); } })().catch(e=>{console.error(e);process.exitCode=1;});
