// Current finalized setup/Send UI. Real local API; explicitly synthetic POI source.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||require('node:path').join(require('node:os').homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
const {spawn}=require('node:child_process'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict');
const ROOT=path.resolve(__dirname,'..'),OUT=process.env.NOOK_TEST_OUTPUT_DIR ? path.resolve(process.env.NOOK_TEST_OUTPUT_DIR) : path.join(ROOT,'deliverables/nook-ui-alignment'),base='http://127.0.0.1:8766';
fs.mkdirSync(OUT,{recursive:true});const temp=fs.mkdtempSync(path.join(os.tmpdir(),'nook-current-ui-'));const log=fs.openSync(path.join(OUT,'server.log'),'w');
let server,browser,page;const checks=[],errors=[],external=[],pids=[];
function check(name,value=true){assert.ok(value,name);checks.push(name);console.log('PASS',name);}
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function start(){const offset=fs.statSync(path.join(OUT,'server.log')).size;server=spawn(process.env.APP_TEST_PYTHON||path.join(ROOT,'.venv/bin/python'),['scripts/nook_poi_fixture_server.py'],{cwd:ROOT,env:{...process.env,APP_DATA_DIR:temp,APP_PORT:'8766',APP_VISION_DISABLED:'1',APP_VOICE_ENABLED:'0',APP_TEXT_MODEL:'',APP_POI_DOWNLOAD_ENABLED:'1'},stdio:['ignore',log,log]});pids.push(server.pid);for(let i=0;i<80;i++){if(server.exitCode!==null)throw Error('Owned server exited');try{if(fs.readFileSync(path.join(OUT,'server.log'),'utf8').slice(offset).includes('Uvicorn running on '+base)&&(await fetch(base+'/api/status')).ok)return;}catch{}await sleep(100);}throw Error('Readiness timeout');}
async function stop(){if(server&&server.exitCode===null){server.kill('SIGTERM');await new Promise(r=>server.once('exit',r));}}
async function count(){return (await(await fetch(base+'/api/status')).json()).item_count;}
async function nav(target){await page.locator(`nav a[data-page=${target}]`).click();await page.locator('#'+target).waitFor({state:'visible'});}
async function ask(text){await page.locator('#utterance').fill(text);await page.locator('#ask').click();}
async function details(){await page.locator('#memory-details').evaluate(e=>e.open=true);}
async function saveManual(name,place){await nav('capture');await details();await page.locator('#item-name').fill(name);await page.locator('#item-location').fill(place);await page.locator('#send-memory').click();await page.locator('#remember-success').waitFor({state:'visible'});}
(async()=>{try{
 await start();browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE||path.join(os.homedir(),'.cache/ms-playwright/chromium-1234/chrome-linux64/chrome'),args:['--disable-gpu','--renderer-process-limit=2']});
 const context=await browser.newContext({viewport:{width:1280,height:1000},reducedMotion:'reduce'});page=await context.newPage();page.setDefaultTimeout(8000);page.on('pageerror',e=>errors.push(e.message));
 await context.route('**/*',r=>{if(!r.request().url().startsWith(base)){external.push(r.request().url());return r.abort();}return r.continue();});
 await page.goto(base);await page.locator('#onboard-next').click();await page.locator('#profile-name').fill('Test user');await page.locator('#setup-next').click();await page.locator('#setup-next').click();await page.locator('#setup-next').click();await page.locator('#onboarding').waitFor({state:'hidden'});
 check('Three-step setup saves profile and reaches Remember',await page.evaluate(()=>localStorage.getItem('nook.profileName')==='Test user'&&localStorage.getItem('nook.setupVersion')==='2'));
 await page.locator('#memory-prompt').fill('My keys are in the hall drawer');await page.locator('#memory-preview').waitFor({state:'visible'});check('Parsed details preview does not save',await count()===0);
 await page.locator('#send-memory').dblclick();await page.locator('#remember-success').waitFor({state:'visible'});check('Explicit Send saves exactly once',await count()===1);
 await nav('talk');check('Voice-off typing fallback',await page.locator('#record').isDisabled());await ask('where are my keys?');await page.getByText('Here is your last record.',{exact:true}).waitFor();check('Real API grounded recall');
 await ask('move "My keys" to "desk"');await page.locator('#approve-proposal').waitFor();check('Action displays exact before and after',(await page.locator('#answer').innerText()).includes('hall drawer')&&(await page.locator('#answer').innerText()).includes('desk'));
 await page.locator('#cancel-proposal').click();check('Action cancel makes no change',(await page.locator('#answer').innerText()).includes('cancelled'));
 await ask('categorize "My keys" as "Everyday"');await page.locator('#approve-proposal').click();await page.getByText('Change saved.',{exact:true}).waitFor();check('Explicit category approval executes deterministic write');
 await ask('rename "My keys" to "House keys"');await page.locator('#approve-proposal').click();await page.getByText('Change saved.',{exact:true}).waitFor();check('Rename proposal approved');
 await ask('remember "Travel keys" at "Bag"');await page.locator('#approve-proposal').click();await page.getByText('Change saved.',{exact:true}).waitFor();check('Create proposal approved',await count()===2);
 await ask('move "missing" to "desk"');await page.getByText('No change proposed.',{exact:true}).waitFor();check('Unknown target cannot create implied record',await count()===2);
 await ask('House keys');await page.getByText('Here is your last record.',{exact:true}).waitFor();await page.screenshot({path:path.join(OUT,'talk-desktop.png'),fullPage:true});
 await nav('capture');await page.locator('#photo-file').setInputFiles(path.join(ROOT,'tests/fixtures/vision/keys.jpg'));await page.locator('#photo-attachment').waitFor({state:'visible'});await details();await page.locator('#item-name').fill('Photo keys');await page.locator('#item-location').fill('Shelf');await page.locator('#review-days').fill('7');await page.locator('#photo-extras').evaluate(e=>e.open=true);await page.locator('#first-region .region-x').fill('0');await page.locator('#first-region .region-y').fill('0');await page.locator('#first-region .region-w').fill('50');await page.locator('#first-region .region-h').fill('50');await page.locator('#add-photo-item').click();await page.locator('.extra-name').fill('Photo ring');await page.screenshot({path:path.join(OUT,'capture-desktop.png'),fullPage:true});await page.locator('#send-memory').click();await page.locator('#remember-success').waitFor({state:'visible'});check('Two reviewed items share one photo',await count()===4);
 await page.locator('#view-saved-memory').click();await page.locator('#detail').waitFor({state:'visible'});check('Photo provenance and freshness visible',(await page.locator('#detail').innerText()).includes('Confirmed imported photo')&&(await page.locator('#detail').innerText()).includes('Recheck after'));
 await page.locator('#new-location').fill('Kitchen');await page.getByRole('button',{name:'Confirm location update',exact:true}).click();await page.getByText('Last recorded: Kitchen',{exact:true}).first().waitFor();check('Move retains historical photo',await page.locator('#detail .history img').count()===1);
 await page.getByRole('button',{name:'Mark moved / unknown'}).click();await page.locator('#confirm-action').click();await page.getByText('Location unknown',{exact:true}).first().waitFor();check('Moved unknown state explicit');await page.locator('#close-detail').click();
 await details();await page.locator('#item-name').fill('Unknown item');await page.locator('#manual-unknown').check();await page.locator('#send-memory').click();await page.locator('#remember-success').waitFor({state:'visible'});check('Manual initial unknown location',await count()===5);
 await nav('saved');await page.locator('#saved .card').first().waitFor();await page.setViewportSize({width:390,height:1100});await page.screenshot({path:path.join(OUT,'saved-mobile.png'),fullPage:true});check('Mobile reflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.locator('#open-places').click();await page.locator('#area-label').fill('Synthetic public area');await page.locator('#area-lat').fill('0');await page.locator('#area-lon').fill('0');await page.locator('#download-area').click();check('Source consent required before fetch',!fs.readFileSync(path.join(OUT,'server.log'),'utf8').includes('SYNTHETIC_SOURCE_BOUNDARY'));await page.locator('#area-consent').check();await page.locator('#download-area').click();await page.waitForFunction(()=>document.querySelector('#area-status').textContent.includes('1 / 250'));check('Synthetic source download saved');await page.locator('#nearby-category').selectOption('cafe');await page.locator('#point-confirm').check();await page.getByRole('button',{name:'Search saved places',exact:true}).click();await page.getByText('Synthetic offline cafe',{exact:true}).waitFor();check('Offline cached query and attribution',(await page.locator('#area-status').innerText()).includes('OpenStreetMap'));
 await page.locator('#close-places').click();await stop();await start();await page.reload();await page.locator('#saved .card').first().waitFor();check('Real backend restart keeps memories',await count()===5);await page.locator('#open-places').click();await page.locator('#area-lat').fill('0');await page.locator('#area-lon').fill('0');await page.locator('#nearby-category').selectOption('cafe');await page.locator('#point-confirm').check();await page.getByRole('button',{name:'Search saved places',exact:true}).click();await page.getByText('Synthetic offline cafe',{exact:true}).waitFor();check('Restart keeps POI provenance and offline query');await page.locator('#close-places').click();
 await nav('capture');await page.locator('#photo-file').setInputFiles({name:'bad.png',mimeType:'image/png',buffer:Buffer.from('invalid')});await page.waitForFunction(()=>document.querySelector('#remember-error').textContent.length>0);check('Malformed upload cannot save',await count()===5);
 let dropped=false;await page.route('**/api/items',async route=>{if(route.request().method()==='POST'&&!dropped){dropped=true;await route.fetch();await route.abort('failed');}else await route.continue();});await details();await page.locator('#item-name').fill('Retry item');await page.locator('#item-location').fill('Drawer');await page.locator('#send-memory').click();await page.waitForFunction(()=>document.querySelector('#send-memory').textContent.includes('Retry'));await page.locator('#send-memory').click();await page.locator('#remember-success').waitFor({state:'visible'});check('Lost save response retries same idempotency key',await count()===6);await page.unroute('**/api/items');
 await nav('talk');await page.route('**/api/chat',async r=>{await sleep(500);await r.fulfill({json:{kind:'unknown',items:[],total:0}}).catch(()=>{});});await ask('Retry item');await page.locator('#cancel-talk').click();await sleep(650);check('Cancelled delayed recall cannot repaint',(await page.locator('#answer').innerText()).includes('Stopped.'));await page.unroute('**/api/chat');
 await page.locator('#open-settings').click();await page.locator('#delete-data-form').evaluate(e=>e.closest('details').open=true);await page.locator('#delete-data-phrase').fill('DELETE ALL LOCAL DATA');await page.locator('#delete-data-button').click();await page.locator('#decline-action').click();check('Declining delete-all preserves records',await count()===6);await page.locator('#delete-data-button').click();await page.locator('#confirm-action').click();await page.locator('#settings').waitFor({state:'hidden'});check('Explicit delete-all clears records',await count()===0);await page.locator('#open-places').click();await page.waitForFunction(()=>document.querySelector('#area-status').textContent.includes('0 / 250'));check('Delete-all clears POI cache',(await page.locator('#area-status').innerText()).includes('0 / 250'));await page.locator('#close-places').click();
 await saveManual('After reset','Desk');check('Writes work after delete-all epoch rotation',await count()===1);check('No page errors',errors.length===0);check('No browser external requests',external.length===0);
 }catch(e){console.error(e);if(page)await page.screenshot({path:path.join(OUT,'failure.png'),fullPage:true}).catch(()=>{});process.exitCode=1;}
 finally{if(browser)await browser.close();await stop();fs.closeSync(log);fs.writeFileSync(path.join(OUT,'browser-results.json'),JSON.stringify({checks,errors,external,server_pids:pids,source:'synthetic fixture; not real source acceptance',passed:!process.exitCode},null,2));fs.rmSync(temp,{recursive:true,force:true});}
})();
